# Generated by Django 6.0.7 on 2026-07-25 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('day_number', models.IntegerField(verbose_name='第几天')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '每日计划',
                'verbose_name_plural': '每日计划',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='行程名称')),
                ('destination', models.CharField(blank=True, default='', max_length=100, verbose_name='目的地')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, unique=True, verbose_name='微信OpenID')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hotel', '酒店'), ('scenic', '景点'), ('restaurant', '餐厅'), ('transport', '交通'), ('other', '其他')], default='scenic', max_length=20, verbose_name='类型')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='地址')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='结束时间')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.dayplan', verbose_name='每日计划')),
            ],
            options={
                'verbose_name': '地点',
                'verbose_name_plural': '地点',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/', verbose_name='图片')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.place', verbose_name='地点')),
            ],
            options={
                'verbose_name': '照片',
                'verbose_name_plural': '照片',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='dayplan',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip', verbose_name='行程'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.user', verbose_name='创建者'),
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('trip', 'date')},
        ),
    ]
