# Generated by Django 6.0.7 on 2026-07-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members_count',
            field=models.IntegerField(default=1, verbose_name='出行人数'),
        ),
    ]
