# Generated by Django 6.0.7 on 2026-07-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_user_avatar_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20, unique=True, verbose_name='坐标(经度,纬度)')),
                ('data', models.JSONField(verbose_name='天气数据')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '天气缓存',
                'verbose_name_plural': '天气缓存',
            },
        ),
    ]
