# Generated by Django 6.0.7 on 2026-07-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_weathercache'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_trips', to='trips.user', verbose_name='成员'),
        ),
    ]
