# Generated by Django 6.0.7 on 2026-07-31 05:25

from django.db import migrations


def migrate_members(apps, schema_editor):
    Trip = apps.get_model('trips', 'Trip')
    User = apps.get_model('trips', 'User')
    all_users = list(User.objects.all())
    for trip in Trip.objects.all():
        # Add creator first
        trip.members.add(trip.user)
        # Add all existing users
        for user in all_users:
            trip.members.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_members'),
    ]

    operations = [
        migrations.RunPython(migrate_members),
    ]
