# Generated by Django 6.0.7 on 2026-07-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_migrate_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='member_order',
            field=models.JSONField(blank=True, default=list, verbose_name='成员排序'),
        ),
    ]
