# Generated by Django 6.0.7 on 2026-08-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_member_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='动态内容')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='位置名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_moments', to='trips.user', verbose_name='点赞用户')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='trips.trip', verbose_name='关联行程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='trips.user', verbose_name='发布者')),
            ],
            options={
                'verbose_name': '游记动态',
                'verbose_name_plural': '游记动态',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MomentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='trips.moment', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moment_comments', to='trips.user', verbose_name='评论者')),
            ],
            options={
                'verbose_name': '动态评论',
                'verbose_name_plural': '动态评论',
                'ordering': ['created_at'],
            },
        ),
    ]
