# Generated by Django 6.0.7 on 2026-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_moment_momentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='distance_km',
            field=models.FloatField(blank=True, null=True, verbose_name='导航距离(km)'),
        ),
        migrations.AddField(
            model_name='place',
            name='end_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='目的地纬度'),
        ),
        migrations.AddField(
            model_name='place',
            name='end_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='目的地'),
        ),
        migrations.AddField(
            model_name='place',
            name='end_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='目的地经度'),
        ),
        migrations.AddField(
            model_name='place',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='出发地纬度'),
        ),
        migrations.AddField(
            model_name='place',
            name='start_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='出发地'),
        ),
        migrations.AddField(
            model_name='place',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='出发地经度'),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('hotel', '酒店'), ('scenic', '景点'), ('restaurant', '餐厅'), ('transport', '交通'), ('drive', '自驾'), ('flight', '飞机'), ('train', '火车'), ('other', '其他')], default='scenic', max_length=20, verbose_name='类型'),
        ),
    ]
