# Generated by Django 6.0.7 on 2026-08-01 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_place_distance_km_place_end_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='', max_length=64, verbose_name='职责')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to='trips.user')),
            ],
            options={
                'verbose_name': '行程成员职责',
                'verbose_name_plural': '行程成员职责',
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
